### ISSUE TITLE
#Fresh Family CR

### ISSUE THREAD

**Issue by t-vdd** [t-vdd/fresh-fam#1]
```yaml

name: #Fresh Family
key: fresh-fam
color: blue
emblem: Lotus_01.png
info:
  logo: /static/img/brands/logo/racf.svg
  description: >
    Fresh family includes a variety of sisterclans that are dominating the EU leaderboard. We have #Fresh Esports, #Fresh2, #Fresh3, #GetFresh, #DeadlyFresh, #FreshFire, #FreshAF, #BeFresh and #FreshlyBaked
clans:
  - name: #Fresh Esports
    tag: 8UUPL298
  - name: #DeadlyFresh
    tag: Q90C0V8

```
